### ISSUE TITLE
Your mod "distant dynasty" has some problems

### ISSUE THREAD

**Issue by CloudAtlas1124** [The-Bees-Decree-Server/SNOWDAY#1]
The paintings in this mod can't show properly, they flicker a lot and they(including the papers) are too bright to watch, also definition is not high enough. Another problem is that the lanterns are too shiny, when I look at them, they make me almost blind, they can't be used as indoor lighting.

**Comment by The-Bees-Decree-Server** [comment]
We will take a look, but textures are supposed to match vanilla valhiem rather than be high def.
When you say lanterns are too shiny, as in the light they emit or the actual lantern itself?

**Comment by CloudAtlas1124** [comment]
I am using vanilla valheim. 
It's the light they emit, I mean the light should be continuous and soft，now the light is flashing
Thank you for making such a good mod btw, I really like it.

**Comment by motleybell** [comment]
I would like to piggyback off of this issue and say that I have some bugs with Distant Dynasties as well. A bunch of the walls do not cast shadows. The foundational support beam piece has an effect of shedding stone or something, and then I will see one or two loot sparkes come off the top of the beam. Nothing is actually dropping or generating, just an odd visual bug. Shadows missing is too bad though. I dunno if it's a bug with my setup, I run a lot of mods. But none of my other build pieces have these issues, including Valkea.
